# Generated by Django 4.2.1 on 2023-05-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('In stock', 'In stock'), ('Out of Stock', 'Out of Stock')], default=4, max_length=50),
            preserve_default=False,
        ),
    ]
