# Generated by Django 4.2.1 on 2023-05-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.CharField(default=4, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
