# Generated by Django 4.2.1 on 2023-05-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_productreview_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='star',
            field=models.IntegerField(default=5),
        ),
    ]
